### ISSUE TITLE
클래스 페이지 삼성인터넷에서 UI 깨지는 현상 수정

### ISSUE THREAD

**Issue by PHJoon** [team-abcdedu/abcdedu-frontend#203]
## 📝 개요

클래스 페이지 삼성인터넷에서 UI 깨지는 현상 수정

## ✅ TODO

- [x] 클래스 메인 페이지 클래스 바로가기 아이템에서 css grid(?) 수정
- [x] 서브 클래스 페이지 타이틀 break-keep 적용

**Comment by imdaxsz** [comment]
issue #202 에서 작업
